"""Database connection layer.

- Local development: SQLite (database/insider_threat.db)
- Vercel/production: Supabase Postgres when SUPABASE_DB_URL or DATABASE_URL is set.

The application was originally written against SQLite.  The small Postgres
adapter below preserves the existing conn.execute(...), fetchone(), fetchall()
and cursor.lastrowid interface so the rest of the application does not need a
large rewrite.
"""

import os
import re
import shutil
import sqlite3

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SOURCE_DB_PATH = os.path.join(BASE_DIR, "database", "insider_threat.db")
_RUNTIME_TMP = os.path.join("/tmp", "threatsim-insider-threat.db")

SUPABASE_DB_URL = os.environ.get("SUPABASE_DB_URL") or os.environ.get("DATABASE_URL")
USE_POSTGRES = bool(SUPABASE_DB_URL)
_IS_VERCEL = os.environ.get("VERCEL") == "1"
DB_PATH = _RUNTIME_TMP if _IS_VERCEL and not USE_POSTGRES else SOURCE_DB_PATH
_initialized = False
_pg_initialized = False


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emp_id TEXT,
    username TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL,
    department TEXT NOT NULL,
    role TEXT NOT NULL,
    email TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    risk_score INTEGER DEFAULT 0,
    last_activity TEXT,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    password TEXT,
    is_admin INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS simulations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    scenario_type TEXT NOT NULL,
    scenario_name TEXT NOT NULL,
    risk_score INTEGER NOT NULL,
    risk_level TEXT NOT NULL,
    indicators TEXT,
    alert_created INTEGER DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    description TEXT,
    status TEXT DEFAULT 'Pending',
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS activity_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    activity_type TEXT NOT NULL,
    description TEXT NOT NULL,
    ip_address TEXT,
    device TEXT,
    timestamp TEXT NOT NULL,
    risk_score INTEGER DEFAULT 0,
    status TEXT DEFAULT 'normal'
);

CREATE TABLE IF NOT EXISTS incidents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    severity TEXT NOT NULL,
    risk_score INTEGER DEFAULT 0,
    incident_type TEXT NOT NULL,
    status TEXT DEFAULT 'Open',
    detected_at TEXT NOT NULL,
    resolved_at TEXT
);

CREATE TABLE IF NOT EXISTS auth_sessions (
    token TEXT PRIMARY KEY,
    kind TEXT NOT NULL,
    user_id INTEGER,
    username TEXT NOT NULL,
    created_at TEXT NOT NULL,
    last_seen TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS schema_meta (
    key TEXT PRIMARY KEY,
    value TEXT
);
"""


def _sqlite_prepare_runtime_database():
    global DB_PATH, _initialized
    if _initialized and os.path.isfile(DB_PATH):
        return
    if _IS_VERCEL:
        DB_PATH = _RUNTIME_TMP
    else:
        try:
            os.makedirs(os.path.dirname(SOURCE_DB_PATH), exist_ok=True)
            test_path = SOURCE_DB_PATH + ".write-test"
            with open(test_path, "ab"):
                pass
            os.remove(test_path)
            DB_PATH = SOURCE_DB_PATH
        except (OSError, PermissionError):
            DB_PATH = _RUNTIME_TMP
    os.makedirs(os.path.dirname(DB_PATH), exist_ok=True)
    if not os.path.exists(DB_PATH):
        if os.path.isfile(SOURCE_DB_PATH) and os.access(SOURCE_DB_PATH, os.R_OK) and DB_PATH != SOURCE_DB_PATH:
            shutil.copyfile(SOURCE_DB_PATH, DB_PATH)
        elif DB_PATH != SOURCE_DB_PATH:
            from database.init_db import create_tables
            conn = sqlite3.connect(DB_PATH)
            try:
                create_tables(conn)
                conn.commit()
            finally:
                conn.close()
    conn = sqlite3.connect(DB_PATH, timeout=15)
    conn.close()
    _initialized = True


def _qmark_to_pyformat(sql):
    """Convert the project's SQLite ? placeholders to psycopg2 %s."""
    return sql.replace("?", "%s")


def _sqlite_datetime_to_postgres(sql):
    return re.sub(r"datetime\('now'\)", "CURRENT_TIMESTAMP", sql, flags=re.IGNORECASE)


class _PGCursor:
    def __init__(self, cursor):
        self._cursor = cursor
        self.lastrowid = None

    def execute(self, sql, params=None):
        self._cursor.execute(sql, params or ())
        if self._cursor.description and self._cursor.description[0].name == "id":
            try:
                row = self._cursor.fetchone()
                if row and isinstance(row, dict):
                    self.lastrowid = row.get("id")
                if row is not None:
                    # Re-execute is not desirable; this path is only used for
                    # INSERT ... RETURNING generated below by _PGConnection.
                    self._prefetched = row
                else:
                    self._prefetched = None
            except Exception:
                self._prefetched = None
        return self

    def fetchone(self):
        if hasattr(self, "_prefetched"):
            row = self._prefetched
            del self._prefetched
            return row
        return self._cursor.fetchone()

    def fetchall(self):
        rows = []
        if hasattr(self, "_prefetched"):
            rows.append(self._prefetched)
            del self._prefetched
        rows.extend(self._cursor.fetchall())
        return rows

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class _PGConnection:
    def __init__(self, raw):
        self._raw = raw

    def execute(self, sql, params=None):
        sql = _sqlite_datetime_to_postgres(_qmark_to_pyformat(sql))
        stripped = sql.lstrip().upper()
        # The application reads cursor.lastrowid after these inserts. PostgreSQL
        # has no lastrowid, so return the generated id transparently.
        if stripped.startswith("INSERT INTO") and "RETURNING" not in stripped:
            table_match = re.match(r"INSERT\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)", sql, re.I)
            if table_match and table_match.group(1).lower() in {"users", "tasks", "incidents", "simulations"}:
                sql = sql.rstrip().rstrip(";") + " RETURNING id"
        cur = self._raw.cursor()
        wrapped = _PGCursor(cur)
        wrapped.execute(sql, params)
        return wrapped

    def commit(self):
        self._raw.commit()

    def rollback(self):
        self._raw.rollback()

    def close(self):
        self._raw.close()


def _ensure_postgres_schema():
    global _pg_initialized
    if _pg_initialized:
        return
    import psycopg2
    from psycopg2.extras import RealDictCursor
    raw = psycopg2.connect(SUPABASE_DB_URL, sslmode="require", connect_timeout=10, cursor_factory=RealDictCursor)
    try:
        raw.autocommit = True
        with raw.cursor() as cur:
            cur.execute(POSTGRES_SCHEMA)
    finally:
        raw.close()
    _pg_initialized = True


def get_db():
    """Return a DB connection compatible with the existing application."""
    if USE_POSTGRES:
        _ensure_postgres_schema()
        import psycopg2
        from psycopg2.extras import RealDictCursor
        raw = psycopg2.connect(SUPABASE_DB_URL, sslmode="require", connect_timeout=10, cursor_factory=RealDictCursor)
        return _PGConnection(raw)

    _sqlite_prepare_runtime_database()
    conn = sqlite3.connect(DB_PATH, timeout=15)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    try:
        conn.execute("PRAGMA journal_mode = WAL")
    except sqlite3.DatabaseError:
        pass
    return conn


def dict_from_row(row):
    if row is None:
        return None
    if isinstance(row, dict):
        return dict(row)
    return dict(row)
